version: '3'
services:
    postgres:
        image: postgres:10
        ports:
            - 5432:5432
        volumes:
            - dbvolume:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=pathe
            - POSTGRES_PASSWORD=pathe
            - PGDATA=/var/lib/postgresql/data/pgdata
volumes:
    dbvolume: {}
