version: "3.8"

services:
  pathe-api:
    container_name: pathe-api
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    restart: unless-stopped
    ports:
      - 4000:4000
    depends_on:
      - postgres
    command: yarn start
    volumes:
      - ./:/app
  postgres:
    image: postgres:10
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - dbvolume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=pathe
      - POSTGRES_PASSWORD=pathe
      - PGDATA=/var/lib/postgresql/data/pgdata

volumes:
  dbvolume: {}
