export enum Cities {
  Amsterdam = "Amsterdam",
  Utrecht = "Utrecht",
  Groningen = "Groningen",
  Rotterdam = "Rotterdam",
  DenHaag = "Den Haag",
  Eindhoven = "Eindhoven",
  Helmond = "Helmond",
  Zaandam = "Zaandam",
  Delft = "Delft",
  Tilburg = "Tilburg",
  Breda = "Breda",
  Haarlem = "Haarlem",
  Amersfoort = "Amersfoort",
  Arnhem = "Arnhem",
  Zwolle = "Zwolle",
  Ede = "Ede",
  Nijmegen = "Nijmegen",
  Schiedam = "Schiedam",
  Leeuwarden = "Leeuwarden",
}

export type PatheCinema = { id: number; name: string; city: Cities }

export const cinemas: PatheCinema[] = [
  { id: 1, name: "City", city: Cities.Amsterdam },
  { id: 2, name: "Tuschinski", city: Cities.Amsterdam },
  { id: 3, name: "Rembrandt Utrecht", city: Cities.Utrecht },
  { id: 4, name: "Groningen", city: Cities.Groningen },
  { id: 5, name: "Buitenhof", city: Cities.Rotterdam },
  { id: 6, name: "Schouwburgplein", city: Cities.Rotterdam },
  { id: 7, name: "Scheveningen", city: Cities.DenHaag },
  { id: 8, name: "Eindhoven", city: Cities.Eindhoven },
  { id: 9, name: "Arena", city: Cities.Amsterdam },
  { id: 10, name: "De Munt", city: Cities.Amsterdam },
  { id: 11, name: "Helmond", city: Cities.Helmond },
  { id: 12, name: "De Kuip", city: Cities.Rotterdam },
  { id: 13, name: "Spuimarkt", city: Cities.DenHaag },
  { id: 14, name: "Zaandam", city: Cities.Zaandam },
  { id: 17, name: "Maastricht", city: Cities.Zaandam },
  { id: 18, name: "Delft", city: Cities.Delft },
  { id: 19, name: "Tilburg Centrum", city: Cities.Tilburg },
  { id: 20, name: "Breda", city: Cities.Breda },
  { id: 22, name: "Haarlem", city: Cities.Haarlem },
  { id: 23, name: "Amersfoort", city: Cities.Amersfoort },
  { id: 27, name: "Arnhem", city: Cities.Arnhem },
  { id: 28, name: "Zwolle", city: Cities.Zwolle },
  { id: 29, name: "Ede", city: Cities.Ede },
  { id: 30, name: "Utrecht Leidsche Rijn", city: Cities.Utrecht },
  { id: 31, name: "Nijmegen", city: Cities.Nijmegen },
  { id: 36, name: "Amsterdam Noord", city: Cities.Amsterdam },
  { id: 37, name: "Tilburg Stappegoor", city: Cities.Tilburg },
  { id: 38, name: "Schiedam", city: Cities.Schiedam },
  { id: 39, name: "Leeuwarden", city: Cities.Leeuwarden },
]

export const cinemasWithFullNames: PatheCinema[] = [
  { id: 1, name: "PathéCity", city: Cities.Amsterdam },
  { id: 2, name: "Koninklijk Theater Tuschinski", city: Cities.Amsterdam },
  { id: 3, name: "Pathé Rembrandt Utrecht", city: Cities.Utrecht },
  { id: 4, name: "Pathé Groningen", city: Cities.Groningen },
  { id: 5, name: "Pathé Buitenhof", city: Cities.Rotterdam },
  { id: 6, name: "Pathé Schouwburgplein", city: Cities.Rotterdam },
  { id: 7, name: "Pathé Scheveningen", city: Cities.DenHaag },
  { id: 8, name: "Pathé Eindhoven", city: Cities.Eindhoven },
  { id: 9, name: "Pathé Arena", city: Cities.Amsterdam },
  { id: 10, name: "Pathé De Munt", city: Cities.Amsterdam },
  { id: 11, name: "Pathé Helmond", city: Cities.Helmond },
  { id: 12, name: "Pathé De Kuip", city: Cities.Rotterdam },
  { id: 13, name: "Pathé Spuimarkt", city: Cities.DenHaag },
  { id: 14, name: "Pathé Zaandam", city: Cities.Zaandam },
  { id: 17, name: "Pathé Maastricht", city: Cities.Zaandam },
  { id: 18, name: "Pathé Delft", city: Cities.Delft },
  { id: 19, name: "Pathé Tilburg Centrum", city: Cities.Tilburg },
  { id: 20, name: "Pathé Breda", city: Cities.Breda },
  { id: 22, name: "Pathé Haarlem", city: Cities.Haarlem },
  { id: 23, name: "Pathé Amersfoort", city: Cities.Amersfoort },
  { id: 27, name: "Pathé Arnhem", city: Cities.Arnhem },
  { id: 28, name: "Pathé Zwolle", city: Cities.Zwolle },
  { id: 29, name: "Pathé Ede", city: Cities.Ede },
  { id: 30, name: "Pathé Utrecht Leidsche Rijn", city: Cities.Utrecht },
  { id: 31, name: "Pathé Nijmegen", city: Cities.Nijmegen },
  { id: 36, name: "Pathé Amsterdam Noord", city: Cities.Amsterdam },
  { id: 37, name: "Pathé Tilburg Stappegoor", city: Cities.Tilburg },
  { id: 38, name: "Pathé Schiedam", city: Cities.Schiedam },
  { id: 39, name: "Pathé Leeuwarden", city: Cities.Leeuwarden },
]

// [15, ''],
// [16, ''],
// [21, ''],
// [24, ''],
// [25, ''],
// [26, ''],
// [32, ''],
// [33, ''],
// [34, ''],
// [35, ''],
